### PR TITLE
clean mirrors

### PR DESCRIPTION
**Pull request by xaniasd**
clean entry per mirror, with a boolean parameter to enable it (or not)

### CODE REVIEW

**Comment by xaniasd** [comment]
ping @jtopjian

**Comment by dvorak** [comment]
I accidentally duplicated your work.  Don't we also want a flag to turn on auto clean?  My PR is #9

**Comment by jtopjian** [comment]
Hi all,

I'm sorry for the late reply on this. 

From reviewing PR #9, it looks like cleaning can be rolled into the existing apt-mirror cron. Are there benefits to having a second cron?

**Comment by xaniasd** [comment]
@dvorak no worries and yes, autoclean is good to have, so thanks for chipping in.
@jtopjian (minor) benefit is cleaner code (avoiding the complex command), furthermore clean job is scheduled at a different time. But we can merge them if you feel strongly about it. More important IMHO is to make the time configurable. Maybe @dvorak can add this to his PR? 

I'll close this one, thanks!

**Pull request closed without merging**
